# For deployment:
# 1. Package application in Docker image
# 2. Push docker image into Docker hub
# 3. Pull Docker image inside the server
# 4. Start application using the new image on the server




version: '3.4'

services:

  web:
    image: marto1003/online_marketplace:2023_08
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env
    volumes:
      - /tmp/app-resources/static:/app/static
    platform: linux/amd64
    command: gunicorn --bind=0.0.0.0:8000 online_marketplace.wsgi:application
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Taralej
      POSTGRES_USER: postgres-user
      POSTGRES_DB: marketplace_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - /tmp/for_deploy/static:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web